config/routes.rb
Rails.application.routes.draw do
  resources :bubbles

end

app/models/bubble.rb
class Bubble < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bubbles_controller.rb
class BubblesController < ApplicationController
  before_action :set_bubble, only: [:show, :edit, :update, :destroy]

  # GET /bubbles
  # GET /bubbles.json
  def index
    @bubbles = Bubble.all
  end

  # GET /bubbles/1
  # GET /bubbles/1.json
  def show
  end

  # GET /bubbles/new
  def new
    @bubble = Bubble.new
  end

  # GET /bubbles/1/edit
  def edit
  end

  # POST /bubbles
  # POST /bubbles.json
  def create
    @bubble = Bubble.new(bubble_params)

    respond_to do |format|
      if @bubble.save
        format.html { redirect_to @bubble, notice: 'Bubble was successfully created.' }
        format.json { render :show, status: :created, location: @bubble }
      else
        format.html { render :new }
        format.json { render json: @bubble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bubbles/1
  # PATCH/PUT /bubbles/1.json
  def update
    respond_to do |format|
      if @bubble.update(bubble_params)
        format.html { redirect_to @bubble, notice: 'Bubble was successfully updated.' }
        format.json { render :show, status: :ok, location: @bubble }
      else
        format.html { render :edit }
        format.json { render json: @bubble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bubbles/1
  # DELETE /bubbles/1.json
  def destroy
    @bubble.destroy
    respond_to do |format|
      format.html { redirect_to bubbles_url, notice: 'Bubble was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bubble
      @bubble = Bubble.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bubble_params
      params.require(:bubble).permit(:title, :tags, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bubbles_helper.rb
module BubblesHelper
end

app/views/bubbles/_form.html.slim
= form_for @bubble do |f|
  - if @bubble.errors.any?
    #error_explanation
      h2 = "#{pluralize(@bubble.errors.count, "error")} prohibited this bubble from being saved:"
      ul
        - @bubble.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :tags
    = f.text_field :tags
  .field
    = f.label :content
    = f.text_field :content
  .actions = f.submit 'Save'

app/views/bubbles/edit.html.slim
h1 Editing bubble

== render 'form'

= link_to 'Show', @bubble
'|
= link_to 'Back', bubbles_path

app/views/bubbles/index.html.slim
h1 Listing bubbles

table
  thead
    tr
      th Title
      th Tags
      th Content
      th
      th
      th

  tbody
    - @bubbles.each do |bubble|
      tr
        td = bubble.title
        td = bubble.tags
        td = bubble.content
        td = link_to 'Show', bubble
        td = link_to 'Edit', edit_bubble_path(bubble)
        td = link_to 'Destroy', bubble, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Bubble', new_bubble_path

app/views/bubbles/new.html.slim
h1 New bubble

== render 'form'

= link_to 'Back', bubbles_path

app/views/bubbles/show.html.slim
p#notice = notice

p
  strong Title:
  = @bubble.title
p
  strong Tags:
  = @bubble.tags
p
  strong Content:
  = @bubble.content

= link_to 'Edit', edit_bubble_path(@bubble)
'|
= link_to 'Back', bubbles_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlayIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>